IF !DEF(COOKIE_CONSTS)
    DEF COOKIE_CONSTS EQU 1
    
    INCLUDE "hardware.inc/hardware.inc"
    INCLUDE "constants/constants.asm"
    
    DEF COOKIE_MIN_SPEED_Y EQU 1
    DEF COOKIE_SPEED_Y_MASK EQU %1  ; [1, 2]
    DEF COOKIE_SPEED_X_MASK EQU %1  ; [-1, 1]
    
    DEF COOKIE_WIDTH EQU 16
    DEF COOKIE_HEIGHT EQU 16
    
    DEF COOKIE_START_Y EQU 1
    DEF COOKIE_TILE1 EQU 4
    DEF COOKIE_TILE2 EQU 6
    
    DEF MAX_COOKIE_COUNT EQU OAM_COUNT - MAX_MISSILE_COUNT - PLAYER_OBJ_COUNT
    
    DEF STARTING_TARGET_COOKIE_COUNT EQU 4
ENDC
