INCLUDE "constants/player.asm"

DEF MISSILE_SPEED EQU -2

DEF MISSILE_WIDTH EQU 8
DEF MISSILE_HEIGHT EQU 16

DEF MISSILE_DEFAULT_Y EQU PLAYER_DEFAULT_Y - (MISSILE_HEIGHT / 4)
DEF MISSILE_TILE EQU 2

RSRESET
DEF MISSILE_Y_OFFSET RB 1
DEF MISSILE_X_OFFSET RB 1

DEF MAX_MISSILE_COUNT EQU 15
DEF MISSILE_SIZE EQU 1 + 1
